apiVersion: v1
kind: Pod
spec:
  containers:
  - name: tracecompass
    image: eclipse/tracecompass-build-env:22.04
    imagePullPolicy: Always
    tty: true
    command: [ "/bin/sh" ]
    args: ["-c", "/home/tracecompass/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "6Gi"
        cpu: "2000m"
      limits:
        memory: "5Gi"
        cpu: "2000m"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
    - name: tools
      mountPath: /opt/tools
  - name: jnlp
    image: 'eclipsecbi/jenkins-jnlp-agent'
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /home/jenkins/.ssh
      name: volume-known-hosts
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
  - name: tools
    persistentVolumeClaim:
      claimName: tools-claim-jiro-tracecompass
